backend:
  name: github
  repo: EmilBuszylo/gatsby-fiat-fso

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/markdown/front-page/index.md"
        label: "Strona główna"
        name: "front-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "front-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Key Words", name: "keyWords", widget: "string"}
          - {label: "SEO Title", name: "seoTitle", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: Slider_img, name: slider_img, widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          # - {label: Info_card, name: info_card, widget: object, fields: [{label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}, , {label: Link, name: link, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}, {label: Link, name: link, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Link, name: link, widget: string}]}, {label: Title, name: title, widget: string}]}, {label: Image4, name: image4, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}, {label: Link, name: link, widget: string}]}]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/markdown/cennik/index.md"
        label: "Cennik"
        name: "pircing"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cennik"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Title", name: "seoTitle", widget: "string"}
          - {label: "Key Words", name: "keyWords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/markdown/nasze-auto/index.md"
        label: "Nasze auto"
        name: "nasze auto"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "nasze-auto"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Key Words", name: "keyWords", widget: "string"}
          - {label: "SEO Title", name: "seoTitle", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/markdown/oferta/index.md"
        label: "Oferta"
        name: "oferta"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "oferta"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Title", name: "seoTitle", widget: "string"}
          - {label: "Key Words", name: "keyWords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/markdown/o-nas/index.md"
        label: "O nas"
        name: "o nas"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "o-nas"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Title", name: "seoTitle", widget: "string"}
          - {label: "Key Words", name: "keyWords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
